// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Read from environment variables instead of hardcoding tokens
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

// Enhanced validation and debugging
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Missing Supabase environment variables:');
  console.error('- NEXT_PUBLIC_SUPABASE_URL:', SUPABASE_URL ? '✅' : '❌ Missing');
  console.error('- NEXT_PUBLIC_SUPABASE_ANON_KEY:', SUPABASE_PUBLISHABLE_KEY ? '✅' : '❌ Missing');
  throw new Error('Missing Supabase environment variables. Please check your .env.local file.');
}

// Detect fake/example values
if (SUPABASE_URL.includes('xyzcompany') || SUPABASE_PUBLISHABLE_KEY.includes('SUPABASE_ANON_KEY_EXEMPLE')) {
  console.error('❌ FAKE VALUES DETECTED:');
  console.error('- URL contains "xyzcompany":', SUPABASE_URL);
  console.error('- Key contains example value:', SUPABASE_PUBLISHABLE_KEY);
  throw new Error('⚠️ Veuillez configurer de vraies valeurs Supabase dans .env.local\n\n' +
    'Étapes:\n' +
    '1. Créez un projet sur https://supabase.com\n' +
    '2. Copiez votre URL et clé ANON depuis Settings > API\n' +
    '3. Mettez à jour votre fichier .env.local');
}

// Validate URL format
try {
  new URL(SUPABASE_URL);
  if (!SUPABASE_URL.includes('supabase.co')) {
    console.warn('⚠️ URL does not appear to be a valid Supabase URL:', SUPABASE_URL);
  }
} catch {
  console.error('❌ Invalid Supabase URL format:', SUPABASE_URL);
  throw new Error(`Invalid Supabase URL: ${SUPABASE_URL}`);
}

// Singleton pattern pour éviter les instances multiples
let supabaseClient: any = null;

// Test Supabase connectivity
const testSupabaseConnection = async () => {
  try {
    const response = await fetch(`${SUPABASE_URL}/rest/v1/`, {
      method: 'HEAD',
      headers: {
        'apikey': SUPABASE_PUBLISHABLE_KEY,
        'Authorization': `Bearer ${SUPABASE_PUBLISHABLE_KEY}`,
      }
    });
    
    if (!response.ok) {
      console.error('❌ Supabase connection test failed:', response.status, response.statusText);
      console.error('🔄 Using fallback mode to prevent crashes');
      return false;
    }
    
    console.log('✅ Supabase connection test passed');
    return true;
  } catch (error) {
    console.error('❌ Supabase connection test error:', error);
    console.error('🔄 Using fallback mode to prevent crashes');
    return false;
  }
};

// Créer le client singleton
const createSupabaseClient = () => {
  if (supabaseClient) {
    console.log('🔄 Using existing Supabase client instance');
    return supabaseClient;
  }

  console.log('🔗 Creating new Supabase client instance');
  console.log('🔗 Supabase client initialized with URL:', SUPABASE_URL);
  console.log('🔑 Anon key length:', SUPABASE_PUBLISHABLE_KEY?.length || 0);
  console.log('🔑 Anon key preview:', SUPABASE_PUBLISHABLE_KEY?.substring(0, 20) + '...');

  try {
    supabaseClient = createClient<Database>(
      SUPABASE_URL, 
      SUPABASE_PUBLISHABLE_KEY,
      {
        auth: {
          persistSession: true,
          autoRefreshToken: true,
          detectSessionInUrl: true,
          flowType: 'pkce',
        }
      }
    );
    
    // Test connection asynchronously
    testSupabaseConnection();
    
  } catch (error) {
    console.error('❌ Failed to create Supabase client:', error);
    console.error('🔄 Using fallback mode');
    
    // Import fallback client
    const { supabase: fallbackClient } = require('./client-fallback');
    supabaseClient = fallbackClient;
  }

  return supabaseClient;
};

// Exporter le client singleton
export const supabase = createSupabaseClient();
