// This file is automatically generated. Do not edit it directly.
// Types are generated from the Supabase database schema using the Supabase CLI.
 

import type { Database as DB } from './database.types';

export type Database = DB;

// Re-export commonly used types for convenience
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];
export type Functions<T extends keyof Database['public']['Functions']> = Database['public']['Functions'][T];

// Types pour les nouvelles tables (manquantes dans la génération auto)
export interface Lead {
  id: string;
  project_id: string;
  client_id: string;
  professional_id?: string;
  qualification_score: number;
  status: 'hot' | 'warm' | 'cold';
  urgency: 'low' | 'medium' | 'high' | 'urgent';
  timeline: string;
  contact_info: {
    email: string;
    phone?: string;
    name: string;
  };
  project_details: {
    work_type: string;
    surface?: number;
    rooms?: number;
    specific_requirements?: string;
  };
  created_at: string;
  updated_at: string;
}

export interface LeadInsert {
  project_id: string;
  client_id: string;
  professional_id?: string;
  qualification_score: number;
  status: 'hot' | 'warm' | 'cold';
  urgency: 'low' | 'medium' | 'high' | 'urgent';
  timeline: string;
  contact_info: {
    email: string;
    phone?: string;
    name: string;
  };
  project_details: {
    work_type: string;
    surface?: number;
    rooms?: number;
    specific_requirements?: string;
  };
}

export interface LeadUpdate {
  project_id?: string;
  client_id?: string;
  professional_id?: string;
  qualification_score?: number;
  status?: 'hot' | 'warm' | 'cold';
  urgency?: 'low' | 'medium' | 'high' | 'urgent';
  timeline?: string;
  contact_info?: {
    email: string;
    phone?: string;
    name: string;
  };
  project_details?: {
    work_type: string;
    surface?: number;
    rooms?: number;
    specific_requirements?: string;
  };
}

export interface LeadForSale {
  id: string;
  client_id: string;
  title: string;
  category: string;
  city: string;
  budget_min: number;
  budget_max: number;
  description: string;
  qualification_score: number;
  status: 'hot' | 'warm' | 'cold';
  urgency: 'low' | 'medium' | 'high' | 'urgent';
  timeline: string;
  contact_info: {
    email: string;
    phone?: string;
    name: string;
  };
  project_details: {
    work_type: string;
    surface?: number;
    rooms?: number;
    specific_requirements?: string;
  };
  price: number;
  is_available: boolean;
  sold_count: number;
  max_sales: number;
  created_at: string;
  updated_at: string;
}

export interface LeadForSale {
  id: string;
  project_id: string;
  client_id: string;
  title: string;
  category: string;
  city: string;
  budget_min: number;
  budget_max: number;
  description: string;
  qualification_score: number;
  status: 'hot' | 'warm' | 'cold';
  urgency: 'low' | 'medium' | 'high' | 'urgent';
  timeline: string;
  contact_info: {
    email: string;
    phone?: string;
    name: string;
  };
  project_details: {
    work_type: string;
    surface?: number;
    rooms?: number;
    specific_requirements?: string;
  };
  price: number;
  is_available: boolean;
  sold_count: number;
  max_sales: number;
  created_at: string;
  updated_at: string;
}

export interface LeadPurchase {
  id: string;
  lead_id: string;
  buyer_id: string;
  purchase_price: number;
  payment_status: 'pending' | 'completed' | 'failed' | 'refunded';
  contact_details_revealed: boolean;
  access_granted_at?: string;
  purchased_at: string;
  created_at: string;
  updated_at: string;
}

export interface PlanningEvent {
  id: string;
  project_id: string;
  professional_id: string;
  client_id: string;
  title: string;
  description?: string;
  event_date: string;
  event_time: string;
  duration: number;
  location: string;
  type: 'phone' | 'video' | 'inperson';
  status: 'scheduled' | 'confirmed' | 'completed' | 'cancelled' | 'no_show';
  notes?: string;
  created_at: string;
  updated_at: string;
}

// Project reference: ofiiepwxvhoflfjcrhop
// Last updated: 2026-02-25T06:29:48.635635
